<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260504185651 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Создание таблицы Pictures';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE IF NOT EXISTS pictures(
            id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
            name VARCHAR(50) NOT NULL,
            image TEXT NOT NULL,
            description VARCHAR(500) DEFAULT NULL,
            category VARCHAR(255) NOT NULL)');

        $this->addSql('CREATE INDEX idx_category ON pictures (category)');

    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP INDEX idx_category');
        $this->addSql('DROP TABLE pictures');
    }
}